services:
  mongo:
    image: mongo
    container_name: taskflow-mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "localdev"
      MONGO_INITDB_ROOT_PASSWORD: "Localdev123"
    volumes:
      - mongo_data:/data/db

  mongoexpress:
    image: mongo-express
    restart: unless-stopped
    container_name: taskflow-mongoexpress
    ports:
      - "3100:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "localdev"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "Localdev123"
      # Basic credentials for logging into the web panel UI at port 3100
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: "localdev"
      ME_CONFIG_BASICAUTH_PASSWORD: "Localdev@123"

  # redis and redisinsights
  redis:
    image: redis:8.10-alpine
    container_name: taskflow-redis
    restart: unless-stopped
    ports:
      - "6311:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # redisinsight:
  #   image: redis/redisinsight:latest
  #   container_name: taskflow-redisinsight
  #   restart: unless-stopped
  #   ports:
  #     - "5540:5540"
  #   environment:
  #     RI_REDIS_HOST: "redis"
  #     RI_REDIS_PORT: 6379
  #   volumes:
  #     - redisinsight_data:/data
  #   depends_on:
  #     - redis

volumes:
  mongo_data:
  redis_data:
  redisinsight_data:
